### ISSUE TITLE
mods\item-colors.lua - error when opening bank before bag

### ISSUE THREAD

**Issue by GryllsAddons** [shagu/ShaguTweaks#38] opened 2023-04-25 18:53 UTC
Just noticed an error that occurs when opening the bank before opening the bags. 
I believe this is because line 178 references "bag" instead of "bank".

Replacing bag with bank will correct the issue:
```
button.ShaguTweaks_border:SetBackdropBorderColor(defcolor["bank"][1], defcolor["bank"][2], defcolor["bank"][3], 1)
```

Cheers!

**Comment by shagu** [comment] 2024-11-08 21:31
Sorry, I have been lazy and left this open, because I have never been able to reproduce the error.

Anyhow, I just wanted to let you know that it's now fixed via: https://github.com/shagu/ShaguTweaks/commit/95d998bd73035ad8faf7ae368240e264a8d03bc2

I sadly still couldn't reproduced it yet, but as it's just right this way so it had to be changed :'D

Really sorry that I haven't responded earlier, it just got lost.
Thanks for the report and the solution :+1:

**Closed by shagu** 2024-11-08 21:31 UTC
